
import React from 'react';
import { Star } from 'lucide-react';

const Testimonials: React.FC = () => {
  const testimonials = [
    {
      name: "Sarah Johnson",
      position: "Healthcare Administrator",
      content: "Health Insurance Claims GPT has revolutionized how we handle patient claims. The AI's ability to accurately identify billing codes and suggest appeal strategies has increased our successful claim rate by 37%.",
      rating: 5
    },
    {
      name: "Michael Chen",
      position: "Medical Billing Specialist",
      content: "I've worked in medical billing for 15 years, and this tool is a game-changer. It pulls accurate Medicare fee data and helps patients understand their actual out-of-pocket costs with remarkable precision.",
      rating: 5
    },
    {
      name: "Dr. Emily Rodriguez",
      position: "Primary Care Physician",
      content: "My patients love that I can provide them with accurate insurance estimates using Health Insurance Claims GPT. It strengthens trust and helps them make informed decisions about their care.",
      rating: 4
    },
    {
      name: "Robert Williams",
      position: "Patient Advocate",
      content: "The appeal letters generated by this AI have helped dozens of my clients overturn wrongful claim denials. It knows exactly which regulations to cite and how to format documentation properly.",
      rating: 5
    }
  ];

  return (
    <section className="section-padding relative overflow-hidden bg-cyber-dark/50">
      <div className="container mx-auto px-6">
        <div className="max-w-3xl mx-auto text-center mb-16">
          <div className="inline-block mb-4 px-3 py-1 rounded-full bg-cyber-purple/10 border border-cyber-purple/30 text-cyber-purple text-xs font-medium">
            Customer Success Stories
          </div>
          <h2 className="text-3xl md:text-4xl font-bold mb-4 text-white">
            What Healthcare Professionals Are Saying
          </h2>
          <p className="text-white/70 text-lg">
            Health Insurance Claims GPT is trusted by medical professionals and patients alike.
          </p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {testimonials.map((testimonial, index) => (
            <div 
              key={index} 
              className="glassmorphism rounded-xl p-6 flex flex-col h-full hover:border-white/20 transition-all duration-300"
            >
              <div className="flex mb-4">
                {[...Array(5)].map((_, i) => (
                  <Star 
                    key={i}
                    className={`w-4 h-4 ${i < testimonial.rating ? 'text-yellow-400 fill-yellow-400' : 'text-gray-500'}`}
                  />
                ))}
              </div>
              <p className="text-white/80 mb-6 flex-grow italic text-sm">"{testimonial.content}"</p>
              <div>
                <p className="font-semibold text-white">{testimonial.name}</p>
                <p className="text-xs text-white/60">{testimonial.position}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
      
      {/* Decorative elements */}
      <div className="absolute -top-40 left-1/4 w-96 h-96 bg-cyber-blue/10 rounded-full filter blur-[120px] -z-10"></div>
    </section>
  );
};

export default Testimonials;
